# Generates GraphMaterials.g.cs: test materials with exactly the properties of the DAS Shader Graphs
# (Reports/Shaders) and of the clip stand-in shader. Run by run.sh.
import json,re,glob,os,sys
root=sys.argv[1]
out=['// generated by gen.py - do not edit','using UnityEngine;','static class GraphMaterials {']
def cs(v): return f'{float(v)}f'
for f in sorted(glob.glob(root+'/Reports/Shaders/*.shadergraph')):
    txt=open(f).read()
    objs=[json.loads(x) for x in re.split(r'\n\n(?=\{)',txt.strip())]
    O={o['m_ObjectId']:o for o in objs}
    g=[o for o in objs if o['m_Type'].endswith('GraphData')][0]
    tgt=[o for o in objs if o['m_Type'].endswith('UniversalTarget')][0]
    name=os.path.basename(f).replace('.shadergraph','').replace('SG_','').replace('_Material','')
    out.append(f'  public static Material {name}(bool withTextures = true) {{')
    out.append(f'    var s = new Shader {{ name = "Shader Graphs/{os.path.basename(f)[:-12]}" }}; var m = new Material(s);')
    for pr in g['m_Properties']:
        p=O[pr['m_Id']]; ref=p.get('m_OverrideReferenceName') or p['m_DefaultReferenceName']; t=p['m_Type'].split('.')[-1]; v=p.get('m_Value')
        if t in('Vector1ShaderProperty',): out.append(f'    m.floats["{ref}"] = {cs(v)};')
        elif t=='BooleanShaderProperty': out.append(f'    m.floats["{ref}"] = {"1f" if v else "0f"};')
        elif t=='ColorShaderProperty': out.append(f'    m.colors["{ref}"] = new Color({cs(v["r"])}, {cs(v["g"])}, {cs(v["b"])}, {cs(v["a"])});')
        elif t=='Texture2DShaderProperty':
            out.append(f'    m.texProps.Add("{ref}"); if (withTextures) m.textures["{ref}"] = new Texture {{ name = "{ref}" }};')
    if tgt['m_SurfaceType']==1: out.append('    m.renderQueue = 3000; m.tags["RenderType"] = "Transparent";')
    else: out.append('    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";')
    out.append('    return m; }')
# stand-in shader properties
sh=open(root+'/Scripts/Shaders/Resources/DAS/ClipSection_Lit.shader').read()
props=re.search(r'Properties\s*\{(.*?)\n    \}',sh,re.S).group(1)
names=[]
for m in re.finditer(r'(?:\[[^\]]*\]\s*)*(_\w+)\s*\("[^"]*",\s*(\w+)',props):
    n,t=m.group(1),m.group(2)
    kind='t' if t=='2D' else 'c' if t=='Color' else 'f'
    names.append(f'"{kind}:{n}"')
out.append('  public static Shader StandIn() { var s = new Shader { name = VehicleMeasurement.ClipMaterials.StandInShaderName };')
out.append('    foreach (var p in new[] { '+', '.join(names)+' }) s.props.Add(p); return s; }')
out.append('}')
open('GraphMaterials.g.cs','w').write('\n'.join(out)+'\n')
print('generated', len(glob.glob(root+'/Reports/Shaders/*.shadergraph')), 'graph materials,', len(names), 'stand-in properties')
