// generated by gen.py - do not edit
using UnityEngine;
static class GraphMaterials {
  public static Material ALLOY(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_ALLOY_Material" }; var m = new Material(s);
    m.floats["_Tiling_UV"] = 1.0f;
    m.floats["_Clip_Z"] = -1.0f;
    m.floats["_Clip_Y"] = 0.0f;
    m.floats["_Clip_X"] = -5.0f;
    m.texProps.Add("_NormalMap"); if (withTextures) m.textures["_NormalMap"] = new Texture { name = "_NormalMap" };
    m.colors["_Base_Map"] = new Color(0.6886792182922363f, 0.6886792182922363f, 0.6886792182922363f, 0.0f);
    m.floats["_Smoothness"] = 0.20000000298023224f;
    m.floats["_Metallic_Map"] = 1.0f;
    m.floats["_NormalValues"] = 1.0f;
    m.floats["_NormalStrength"] = 0.800000011920929f;
    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";
    return m; }
  public static Material Car_Front_Paint(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_Car_Front_Paint_Material" }; var m = new Material(s);
    m.floats["_ClearCoat"] = 1.0f;
    m.floats["_ClearCoatSmoothness"] = 1.0f;
    m.colors["_BaseColor"] = new Color(0.11320751905441284f, 0.11320751905441284f, 0.11320751905441284f, 0.0f);
    m.floats["_Metallic"] = 0.0f;
    m.floats["_Smoothness"] = 1.0f;
    m.floats["_NormalStrength"] = 1.0f;
    m.floats["_Tiling_UV"] = 30.0f;
    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";
    return m; }
  public static Material Car_Paint(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_Car_Paint_Material" }; var m = new Material(s);
    m.floats["_ClearCoat"] = 1.0f;
    m.floats["_ClearCoatSmoothness"] = 1.0f;
    m.colors["_BaseColor"] = new Color(0.11320751905441284f, 0.11320751905441284f, 0.11320751905441284f, 0.0f);
    m.floats["_Metallic"] = 0.0f;
    m.floats["_Smoothness"] = 1.0f;
    m.floats["_NormalStrength"] = 1.0f;
    m.floats["_Tiling_UV"] = 30.0f;
    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";
    return m; }
  public static Material Chrome(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_Chrome_Material" }; var m = new Material(s);
    m.colors["_Base_Map"] = new Color(0.6886792182922363f, 0.6886792182922363f, 0.6886792182922363f, 0.0f);
    m.floats["_Smoothness"] = 0.20000000298023224f;
    m.floats["_Metallic_Map"] = 1.0f;
    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";
    return m; }
  public static Material Glass(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_Glass_Material" }; var m = new Material(s);
    m.floats["_Alpha"] = 0.20000000298023224f;
    m.floats["_MetallicValues"] = 0.0f;
    m.floats["_RoughnessValues"] = 1.0f;
    m.colors["_Color"] = new Color(0.1603773832321167f, 0.1603773832321167f, 0.1603773832321167f, 0.0f);
    m.floats["_ClearCoatSmoothness"] = 1.0f;
    m.floats["_ClearCoat"] = 1.0f;
    m.colors["_Emission_color"] = new Color(0.0f, 0.0f, 0.0f, 0.0f);
    m.renderQueue = 3000; m.tags["RenderType"] = "Transparent";
    return m; }
  public static Material LEATHER(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_LEATHER_Material" }; var m = new Material(s);
    m.texProps.Add("_BaseMap"); if (withTextures) m.textures["_BaseMap"] = new Texture { name = "_BaseMap" };
    m.floats["_RoughnessLevel"] = 1.0f;
    m.floats["_Tiling_UV"] = 6.0f;
    m.texProps.Add("_NormalMap"); if (withTextures) m.textures["_NormalMap"] = new Texture { name = "_NormalMap" };
    m.texProps.Add("_RoughnessMap"); if (withTextures) m.textures["_RoughnessMap"] = new Texture { name = "_RoughnessMap" };
    m.texProps.Add("_MetallicMap"); if (withTextures) m.textures["_MetallicMap"] = new Texture { name = "_MetallicMap" };
    m.floats["_BaseColorLevel"] = 1.100000023841858f;
    m.floats["_Use_BaseMap"] = 0f;
    m.colors["_BaseColor"] = new Color(0.4905660152435303f, 0.4905660152435303f, 0.4905660152435303f, 0.0f);
    m.floats["_NormalStrength"] = 0.6000000238418579f;
    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";
    return m; }
  public static Material Light(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_Light_Material" }; var m = new Material(s);
    m.floats["_MetallicValues"] = 0.0f;
    m.floats["_RoughnessValues"] = 1.0f;
    m.colors["_Base_Map"] = new Color(0.1603773832321167f, 0.1603773832321167f, 0.1603773832321167f, 0.0f);
    m.colors["_Emission_Map"] = new Color(1.0f, 1.0f, 1.0f, 0.0f);
    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";
    return m; }
  public static Material Plastic_FrontSide(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_Plastic_FrontSide_Material" }; var m = new Material(s);
    m.texProps.Add("_BaseMap"); if (withTextures) m.textures["_BaseMap"] = new Texture { name = "_BaseMap" };
    m.floats["_RoughnessLevel"] = 1.0f;
    m.floats["_Tiling_UV"] = 5.0f;
    m.texProps.Add("_NormalMap"); if (withTextures) m.textures["_NormalMap"] = new Texture { name = "_NormalMap" };
    m.texProps.Add("_RoughnessMap"); if (withTextures) m.textures["_RoughnessMap"] = new Texture { name = "_RoughnessMap" };
    m.texProps.Add("_MetallicMap"); if (withTextures) m.textures["_MetallicMap"] = new Texture { name = "_MetallicMap" };
    m.floats["_BaseColorLevel"] = 1.100000023841858f;
    m.floats["_Use_BaseMap"] = 0f;
    m.colors["_BaseColor"] = new Color(0.0f, 0.0f, 0.0f, 0.0f);
    m.floats["_NormalStrenght"] = 1.0f;
    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";
    return m; }
  public static Material Plastic(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_Plastic_Material" }; var m = new Material(s);
    m.texProps.Add("_BaseMap"); if (withTextures) m.textures["_BaseMap"] = new Texture { name = "_BaseMap" };
    m.floats["_RoughnessLevel"] = 1.0f;
    m.floats["_Tiling_UV"] = 5.0f;
    m.texProps.Add("_NormalMap"); if (withTextures) m.textures["_NormalMap"] = new Texture { name = "_NormalMap" };
    m.texProps.Add("_RoughnessMap"); if (withTextures) m.textures["_RoughnessMap"] = new Texture { name = "_RoughnessMap" };
    m.texProps.Add("_MetallicMap"); if (withTextures) m.textures["_MetallicMap"] = new Texture { name = "_MetallicMap" };
    m.floats["_BaseColorLevel"] = 1.100000023841858f;
    m.floats["_Use_BaseMap"] = 0f;
    m.colors["_BaseColor"] = new Color(0.0f, 0.0f, 0.0f, 0.0f);
    m.floats["_NormalStrenght"] = 1.0f;
    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";
    return m; }
  public static Material Rubber(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_Rubber_Material" }; var m = new Material(s);
    m.texProps.Add("_BaseMap"); if (withTextures) m.textures["_BaseMap"] = new Texture { name = "_BaseMap" };
    m.floats["_RoughnessLevel"] = 1.0f;
    m.floats["_Tiling_UV"] = 5.0f;
    m.texProps.Add("_NormalMap"); if (withTextures) m.textures["_NormalMap"] = new Texture { name = "_NormalMap" };
    m.texProps.Add("_RoughnessMap"); if (withTextures) m.textures["_RoughnessMap"] = new Texture { name = "_RoughnessMap" };
    m.texProps.Add("_MetallicMap"); if (withTextures) m.textures["_MetallicMap"] = new Texture { name = "_MetallicMap" };
    m.floats["_BaseColorLevel"] = 1.100000023841858f;
    m.floats["_Use_BaseMap"] = 0f;
    m.colors["_BaseColor"] = new Color(0.0f, 0.0f, 0.0f, 0.0f);
    m.floats["_NormalStrength"] = 0.800000011920929f;
    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";
    return m; }
  public static Material Seat(bool withTextures = true) {
    var s = new Shader { name = "Shader Graphs/SG_Seat_Material" }; var m = new Material(s);
    m.texProps.Add("_BaseMap"); if (withTextures) m.textures["_BaseMap"] = new Texture { name = "_BaseMap" };
    m.floats["_Clip_Z"] = -1.0f;
    m.floats["_Clip_Y"] = 0.0f;
    m.floats["_Clip_X"] = -5.0f;
    m.floats["_RoughnessLevel"] = 0.0f;
    m.floats["_Tiling_UV"] = 3.0f;
    m.texProps.Add("_NormalMap"); if (withTextures) m.textures["_NormalMap"] = new Texture { name = "_NormalMap" };
    m.texProps.Add("_RoughnessMap"); if (withTextures) m.textures["_RoughnessMap"] = new Texture { name = "_RoughnessMap" };
    m.texProps.Add("_MetallicMap"); if (withTextures) m.textures["_MetallicMap"] = new Texture { name = "_MetallicMap" };
    m.floats["_BaseColorLevel"] = 1.100000023841858f;
    m.floats["_Use_BaseMap"] = 1f;
    m.colors["_BaseColor"] = new Color(0.0f, 0.0f, 0.0f, 0.0f);
    m.floats["_NormalStrength"] = 1.0f;
    m.renderQueue = 2000; m.tags["RenderType"] = "Opaque";
    return m; }
  public static Shader StandIn() { var s = new Shader { name = VehicleMeasurement.ClipMaterials.StandInShaderName };
    foreach (var p in new[] { "c:_BaseColor", "t:_BaseMap", "f:_UseBaseMap", "f:_BaseMapLevel", "f:_Metallic", "t:_MetallicMap", "f:_UseMetallicMap", "f:_Smoothness", "t:_SmoothnessMap", "f:_UseSmoothnessMap", "t:_BumpMap", "f:_BumpScale", "f:_UseBumpMap", "f:_ClearCoatMask", "f:_ClearCoatSmoothness", "c:_EmissionColor", "f:_Triplanar", "f:_TriplanarTiling", "f:_DASSurfaceAlpha", "f:_Opacity", "c:_CutFaceTint", "f:_Surface", "f:_SrcBlend", "f:_DstBlend", "f:_ZWrite", "f:_Cull", "f:_DASKeepTransparent" }) s.props.Add(p); return s; }
}
